### ISSUE TITLE
如果能支持st2...

### ISSUE THREAD

**Issue by lwbjing** [gogoyqj/AvalonHelper#1]
也是极好的。。

**Comment by gogoyqj** [comment]
这个我试过，但是sublime 2的自动完成不是太好注入，难道略大，没有搞定

**Comment by IndexXuan** [comment]
弱弱的问句啥时候有vim版，逃...

**Comment by IndexXuan** [comment]
其实早就装了。现在想问下为什么我在sublime3上比如在body里写了ms，提示有ms-controller，接着选择到ms-controller, 然后enter一下出来了是不错，但是代码换行了。。。强迫症受不了，请问是我这有问题还是就这么设计的？ vim用习惯了，都是就地补全啊~

**Comment by gogoyqj** [comment]
@IndexXuan 做了一个自动换行 - -，我看看，弄个配置关掉

@IndexXuan 已经有一个autoBr配置了
